config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web, :at => "/sidekiq"

  get 'authentication/authorize_url'
  get 'authentication/callback'

  resource :mute, only: [:new, :create]

  root "pages#home"
end

app/models/concerns/user/authorization.rb
class User < ActiveRecord::Base
  module Authorization
    def authorize_url
      self.request_token = request_token_object.token
      self.request_token_secret = request_token_object.secret
      save!

      request_token_object.authorize_url
    end

    def request_token_object
      @request_token_object ||= twitter_oauth_client.request_token oauth_callback: ENV['TWITTER_API_CALLBACK_URL'] + '/authentication/callback'
    end

    def twitter_oauth_client
      # TODO: move these credentials to application.rb
      @twitter_oauth_client ||= TwitterOAuth::Client.new consumer_key: ENV['TWITTER_API_KEY'], consumer_secret: ENV['TWITTER_API_SECRET']
    end

    def authorize! oauth_verifier: nil
      access_token = twitter_oauth_client.authorize request_token, request_token_secret, oauth_verifier: oauth_verifier

      if twitter_oauth_client.authorized?
        self.access_token = access_token.token
        self.access_token_secret = access_token.secret
        save!
      else
        raise 'Boom!'
      end
    end
  end
end

app/models/concerns/user/twitter_rest_methods.rb
class User
  module TwitterRestMethods

    extend ActiveSupport::Concern

    def twitter_rest_client
      @twitter_client ||= Twitter::REST::Client.new do |config|
        config.consumer_key        = ENV['TWITTER_API_KEY'] # TODO use app.configuration
        config.consumer_secret     = ENV['TWITTER_API_SECRET'] # TODO use app.configuration
        config.access_token        = access_token
        config.access_token_secret = access_token_secret
      end
    end

    def mute twitter_name
      twitter_rest_client.mute twitter_name
    end

    def unmute twitter_name
      twitter_rest_client.unmute twitter_name
    end

  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include TwitterRestMethods
  include Authorization
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Authentication
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  def authorize_url
    user = User.create!
    redirect_to user.authorize_url
  end

  def callback
    user = User.find_by! request_token: params[:oauth_token]
    user.authorize! oauth_verifier: params[:oauth_verifier]

    session[:user_id] = user.id

    redirect_to new_mute_path
  end
end

app/controllers/concerns/application_controller/authentication.rb
module ApplicationController::Authentication
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/mutes_controller.rb
class MutesController < ApplicationController

  def new
  end

  def create
    current_user.mute params[:twitter_name]
    UnmuteJob.perform_in params.require(:mute)[:unmute_at].to_time, current_user.id, params[:twitter_name]
    redirect_to :new_mute, notice: 'Muted!'
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def notice_block
    return unless notice
    content_tag :p, notice
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShutupTw</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= notice_block %>

<%= yield %>

</body>
</html>

app/views/mutes/new.html.erb
<%= form_tag mute_path do |f| %>
  <%= label_tag 'Mute twitter of' %>
  <%= text_field_tag :twitter_name, nil, style: 'width: 100px' %>
  <%= select(:mute, :unmute_at,
      [
        ['for an hour', 1.hour.from_now],
        ['for a day', 1.day.from_now],
        ['for a week', 1.week.from_now],
        ['for a month', 1.month.from_now],
        ['until World Cup 2014 is over', 'Sun, 14 Jul 2014 00:00:00 +0000']
      ]
      ) %>
  <%= submit_tag 'Do it!' %>
<% end %>

app/views/pages/home.html.erb
<%= image_tag "screenshot.png", id: :screenshot %>
<br>
<%= link_to "Mute annoying people", authentication_authorize_url_path, id: :sign_in %>